# Generated by Django 5.1.3 on 2024-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productin',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='productin',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=255),
        ),
    ]
